{{- if .Values.server.pdb.enabled }}
{{- if and (not .Values.server.pdb.minAvailable) (not .Values.server.pdb.maxUnavailable) }}
{{ fail "'server.pdb.minAvailable' or 'server.pdb.maxUnavailable' must be set when PDB is enabled: 'server.pdb.enabled'" }}
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "varnish-cache.fullname" . }}
  labels:
    {{- include "varnish-cache.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ include "varnish-cache.selectorLabels" . | nindent 6 }}
{{- if .Values.server.pdb.minAvailable }}
  minAvailable: {{ .Values.server.pdb.minAvailable }}
{{- end }}
{{- if .Values.server.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.server.pdb.maxUnavailable }}
{{- end }}
{{- end }}
