{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "varnish-cache.serviceAccountName" . }}
  labels:
    {{- include "varnish-cache.labels" . | nindent 4 }}
    {{- include "varnish-cache.serviceAccountLabels" . | indent 4 }}
  {{- include "varnish-cache.serviceAccountAnnotations" . | indent 2 }}
{{- end }}
